from config.app.config import (
    AlltalkConfig,
    AlltalkConfigApiDef,
    AlltalkConfigCorsSettings,
    AlltalkConfigDebug,
    AlltalkConfigGradioPages,
    AlltalkConfigProxyEndpoint,
    AlltalkConfigProxySettings,
    AlltalkConfigRvcSettings,
    AlltalkConfigTgwUi,
    AlltalkConfigTheme,
    AlltalkMultiEngineManagerConfig,
    AlltalkNewEnginesConfig,
    AlltalkTTSEnginesConfig,
)

__all__ = [
    "AlltalkConfig",
    "AlltalkConfigApiDef",
    "AlltalkConfigCorsSettings",
    "AlltalkConfigDebug",
    "AlltalkConfigGradioPages",
    "AlltalkConfigProxyEndpoint",
    "AlltalkConfigProxySettings",
    "AlltalkConfigRvcSettings",
    "AlltalkConfigTgwUi",
    "AlltalkConfigTheme",
    "AlltalkMultiEngineManagerConfig",
    "AlltalkNewEnginesConfig",
    "AlltalkTTSEnginesConfig",
]
